### PR TITLE
Changes to bulid against iRODS 4.3.x

### PR DESCRIPTION
**Pull request by jasoncoposky**
Massaged some CMake

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Looking good.

Have you seen it run against 4.3.0 yet?

**Comment by korydraughn** [comment]
I think we just go ahead and merge this as is.

This hasn't been released yet, so we'll review it before putting out a release.

@trel Thoughts?

**Comment by trel** [comment]
let's tweak the commit message from "bulid" to "build".

and consider any additional commits for anything we want to tweak.   yes, this is an unreleased repo, so it can be in an unfinished state, so merging is fine if you want.

**Comment by alanking** [comment]
We've decided to merge as-is.

**Pull request merged**
